---
title : Foundit Platform
---

classDiagram
    class User {
        id: int
        firstName: string
        lastName: string
        email: string
        password: string
        created_at: Timestamp
        register()
        login()
        updateProfile()
        reportItem()
        sendMessage()
    }

    class Admin {
        assingRole()
        banUser()
        viewReports()
    }

    class Moderator {
        deleteContent()
        flagPost()
    }

    class Item {
        id: int
        user_id: int
        title: string
        description: text
        category: string
        location: string
        latitude: float
        longtitude: float
        image: string
        status: enum
        reported_at: timestamp
        resolved_at: timestamp 'nullable'
        created_at: timestamp
        updated_at: timestamp
        getDetails()
        updateItem()
        deleteItem()
    }

    class MatchingSystem {
        match_id: int
        lost_item_id: int
        found_item_id: int
        confidence_score: float
        matched_at: timestamp
        findMatches()
        notifyUsers()
        refineMacthes()
    }

    class Notifications {
        id: int
        user_id: int
        message: string
        is_read: boolean
        sent_at: timestamp
        sendNotification()
        markAsRead()
    }

    class Message {
        id: int
        sender_id: int
        reciever_id: int
        content: text
        sent_at: timestamp
        sendMessage()
        deleteMessage()
    }

    class GeolocationService {
        id: int
        post_id: int
        latitude: float
        longtitude: float
        radius: int
        getNearbyMatches()
        filtreByLocation()
    }

    class ImageProcessingService {
        id: int
        post_id
        image_hash: string
        similarity_score: float
        analyzeImage()
        compareImages()
    }

%% Relationships
    User <|-- Admin
    User <|-- Moderator
    User "1" --> "many" Item : posts
    User "1" --> "many" Message : sends
    User "1" --> "many" Message : receives
    User "1" --> "many" Notifications : receives
    MatchingSystem "1" --> "many" Item : matches
    GeolocationService --> MatchingSystem : assists
    ImageProcessingService --> MatchingSystem : analyzes images
