name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl

      - name: Validate composer.json
        run: composer validate --no-check-lock
        working-directory: backend

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        working-directory: backend

      - name: Copy environment file
        run: cp .env.example .env
        working-directory: backend

      - name: Generate app key
        run: php artisan key:generate --ansi
        working-directory: backend

      - name: Run migrations
        run: php artisan migrate --env=testing --no-interaction
        working-directory: backend

      - name: Run tests
        run: php artisan test --env=testing --no-interaction --verbose
        working-directory: backend
