name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: foundit_tests
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: foundit_tests
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl

      - name: Validate composer.json
        run: composer validate --no-check-lock
        working-directory: backend

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        working-directory: backend

      - name: Copy environment file
        run: cp .env.example .env
        working-directory: backend

      - name: Setup testing environment
        run: |
          cp .env.example .env.testing
          echo "DB_CONNECTION=pgsql" >> .env.testing
          echo "DB_HOST=127.0.0.1" >> .env.testing
          echo "DB_PORT=5432" >> .env.testing
          echo "DB_DATABASE=foundit_tests" >> .env.testing
          echo "DB_USERNAME=root" >> .env.testing
          echo "DB_PASSWORD=root" >> .env.testing
        working-directory: backend

      - name: Generate app key
        run: php artisan key:generate --ansi
        working-directory: backend

      - name: Run migrations
        run: php artisan migrate --env=testing --no-interaction
        working-directory: backend

      - name: Run tests
        run: php artisan test --env=testing --no-interaction --verbose
        working-directory: backend

   