name: Frontend CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci
        
      - name: Build Tailwind CSS
        working-directory: ./backend
        run: npm run build

      - name: Run Linting
        working-directory: ./backend
        run: npm run lint