permissions:
  actions: read
  contents: read
  security-events: write

name: Security & IaC Scan
on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]

jobs: 
  terraform-scan:
    name: Terraform Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'
      - name: Terraform fmt check
        run: terraform fmt -check -diff
      - name: tfsec scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          version: latest
      - name: TFLint
        uses: terraform-linters/setup-tflint@v1

  container-scan:
    name: Container CVE Scan
    needs: terraform-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t foundit-backend:latest ./backend
      - name: Trivy CVE scan
        uses: aquasecurity/trivy-action@0.30.0    # ← correct tag (no “v”) 
        with:
          image-ref: foundit-backend:latest
          format: table

  php-static-analysis:
    name: Laravel Static Analysis
    needs: container-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install dependencies
        working-directory: backend
        run: |
          composer update --prefer-dist --no-interaction
          composer install --prefer-dist --no-interaction
      - name: Run PHPStan
        working-directory: backend
        run: vendor/bin/phpstan analyse app config routes resources/views
      - name: Psalm Security Scan
        working-directory: backend
        run: |
          vendor/bin/psalm --no-interaction --show-info=false --output-format=emacs

  codeql:
    name: CodeQL Analysis (Vue.js)
    needs: php-static-analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
